# Generated by Django 5.2.2 on 2026-02-18 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTSPJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Camera/Stream name', max_length=255)),
                ('rtsp_url', models.CharField(help_text='RTSP URL or camera index (0 for webcam)', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('error', 'Error')], default='pending', max_length=20)),
                ('fps', models.IntegerField(default=15, help_text='Frames per second to capture')),
                ('buffer_size', models.IntegerField(default=16, help_text='Frames to buffer before processing (STEAD requires 16)')),
                ('threshold', models.FloatField(default=0.7, help_text='Anomaly detection threshold (0-1)')),
                ('total_frames_processed', models.BigIntegerField(default=0)),
                ('total_anomalies_detected', models.IntegerField(default=0)),
                ('last_anomaly_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtsp_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RTSP Job',
                'verbose_name_plural': 'RTSP Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnomalyDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_score', models.FloatField()),
                ('label', models.CharField(default='Suspicious', max_length=50)),
                ('frame_start', models.IntegerField(blank=True, null=True)),
                ('frame_end', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_chunk', models.FileField(blank=True, null=True, upload_to='anomaly_videos/')),
                ('model_output', models.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='stead.rtspjob')),
            ],
            options={
                'verbose_name': 'Anomaly Detection',
                'verbose_name_plural': 'Anomaly Detections',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_file', models.FileField(upload_to='uploaded_videos/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('has_anomaly', models.BooleanField(null=True)),
                ('max_anomaly_score', models.FloatField(null=True)),
                ('total_clips', models.IntegerField(null=True)),
                ('anomaly_count', models.IntegerField(null=True)),
                ('result_details', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Upload',
                'verbose_name_plural': 'Video Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
