# Generated by Django 5.2.2 on 2026-02-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='avg_anomaly_score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='fps',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='hls_playlist',
            field=models.CharField(blank=True, help_text='HLS playlist path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='output_video',
            field=models.FileField(blank=True, null=True, upload_to='stead_outputs/'),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='output_video_web',
            field=models.CharField(blank=True, help_text='Web-ready MP4 path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='Thumbnail image path', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='total_frames',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='videoupload',
            name='video_file',
            field=models.FileField(upload_to='stead_uploads/'),
        ),
    ]
