# Generated by Django 5.2.2 on 2026-02-26 11:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0009_merge_20250917_1348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique task identifier', primary_key=True, serialize=False)),
                ('task_name', models.CharField(help_text='Name of the task', max_length=255)),
                ('subprocess_id', models.IntegerField(blank=True, help_text='PID of the spawned subprocess', null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='Time the task started')),
                ('end_time', models.DateTimeField(blank=True, help_text='Time the task finished', null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', help_text='Current state of task', max_length=50)),
                ('log_file', models.CharField(blank=True, help_text='Path to log file', max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the task', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
