# Generated by Django 5.2.2 on 2026-03-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerGithub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(help_text='GitHub Repository URL', max_length=500)),
                ('github_folder', models.CharField(help_text='Path to folder within the repository', max_length=255)),
                ('folder_hash', models.CharField(help_text='Latest commit SHA for this specific folder tree', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time the update check was performed')),
                ('container', models.OneToOneField(help_text='Linked container', on_delete=django.db.models.deletion.CASCADE, related_name='github_info', to='predictor.container')),
            ],
        ),
    ]
